linters:
  enable:
    - gofmt
    - revive
    - govet
    - ineffassign
    - misspell
    - unconvert
    - gocritic
    - goimports

linters-settings:
  revive:
    rules:
      - name: package-comments
        disabled: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocritic